#!/bin/bash

display_date(){
  echo "=== Date & Time ==="
  date
  echo
}

display_users_uptime(){
  echo "=== Uptime ==="
  uptime
  echo
  echo "--- Users ---"
  w
  echo
}

display_cpu_usage(){
  echo "=== CPU Usage ==="
  top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print "CPU Idle: " 100 - $1 "%"}'
  echo
  echo "--- CPU info ---"
  lscpu | grep -E "Model name|CPU(s)|Thread|Core"
  echo
}

display_memory_usage(){
  echo "=== Memory Usage ==="
  free -h
  echo
  echo "--- Swap info ---"
  swapon --show
  echo
}

display_disk_usage(){
  echo "=== Disk Usage ==="
  df -h --total | grep total
  echo
}

display_network_usage(){
  echo "=== Network Usage ==="
  netstat -r
  echo
  echo "--- Socket information ---"
  ss --summary
  echo
  ss -tupln
}



display_date
display_users_uptime
display_cpu_usage
display_memory_usage
display_disk_usage
display_network_usage
